export interface CuratedMovie {
  tmdbId: number;
  title: string;
  year: number;
  language: 'english' | 'hindi' | 'bengali';
  genres: string[];
  tasteTags: string[];
  matchNote: string;
}

export const curatedMovies: CuratedMovie[] = [
  {
    tmdbId: 44826,
    title: 'Barfi!',
    year: 2012,
    language: 'hindi',
    genres: ['romance', 'comedy', 'drama'],
    tasteTags: ['whimsical', 'soft-romance'],
    matchNote: 'Love that is pure, wordless, and beautifully strange — this one is pure heart.',
  },
  {
    tmdbId: 282813,
    title: 'Wake Up Sid',
    year: 2009,
    language: 'hindi',
    genres: ['coming-of-age', 'romance', 'comedy'],
    tasteTags: ['coming-of-age', 'soft-romance'],
    matchNote: 'Growing into yourself, finding your path, and falling in love along the way.',
  },
  {
    tmdbId: 2107,
    title: 'Notting Hill',
    year: 1999,
    language: 'english',
    genres: ['romance', 'comedy'],
    tasteTags: ['filmy-romance', 'soft-romance'],
    matchNote: 'Ordinary person, extraordinary love — and that famous bench. Pure comfort romance.',
  },
  {
    tmdbId: 56715,
    title: 'Tamasha',
    year: 2015,
    language: 'hindi',
    genres: ['romance', 'drama', 'coming-of-age'],
    tasteTags: ['coming-of-age', 'thought-provoking'],
    matchNote: 'About the masks we wear and the courage to be ourselves — and finding love that sees through.',
  },
  {
    tmdbId: 122,
    title: 'The Pursuit of Happyness',
    year: 2006,
    language: 'english',
    genres: ['drama', 'biography'],
    tasteTags: ['social-drama', 'thought-provoking'],
    matchNote: 'Dignity, ambition, and a father\'s love. Hits you right in the chest.',
  },
  {
    tmdbId: 230,
    title: 'Swades',
    year: 2004,
    language: 'hindi',
    genres: ['drama', 'social-political'],
    tasteTags: ['social-drama'],
    matchNote: 'What does home mean? What do we owe our roots? A deeply moral, moving journey.',
  },
  {
    tmdbId: 504,
    title: 'The Namesake',
    year: 2006,
    language: 'english',
    genres: ['drama', 'romance'],
    tasteTags: ['literary-melancholy', 'coming-of-age'],
    matchNote: 'Identity, belonging, love across generations — a film that feels like a beautiful book.',
  },
  {
    tmdbId: 950387,
    title: 'A Man Called Otto',
    year: 2022,
    language: 'english',
    genres: ['comedy', 'drama'],
    tasteTags: ['comfort-cute', 'thought-provoking'],
    matchNote: 'A grumpy heart that learns to feel again. Tears and warmth in equal measure.',
  },
  {
    tmdbId: 121,
    title: 'Lady Bird',
    year: 2017,
    language: 'english',
    genres: ['coming-of-age', 'drama', 'comedy'],
    tasteTags: ['coming-of-age'],
    matchNote: 'Trying to find yourself while pushing away the people who love you most. So real.',
  },
  {
    tmdbId: 1903,
    title: 'Anand',
    year: 1971,
    language: 'hindi',
    genres: ['drama'],
    tasteTags: ['thought-provoking', 'comfort-cute'],
    matchNote: 'A celebration of life in the face of mortality. Babu Moshai — pure timeless magic.',
  },
  {
    tmdbId: 11395,
    title: 'Haider',
    year: 2014,
    language: 'hindi',
    genres: ['drama', 'thriller', 'social-political'],
    tasteTags: ['social-drama', 'literary-melancholy'],
    matchNote: 'Hamlet in Kashmir. Poetry, grief, and political anguish — devastatingly beautiful.',
  },
  {
    tmdbId: 64499,
    title: 'Hridayam',
    year: 2022,
    language: 'hindi',
    genres: ['romance', 'coming-of-age', 'drama'],
    tasteTags: ['coming-of-age', 'soft-romance'],
    matchNote: 'Life phases, old love, new love, growing through it all. A whole lifetime in one film.',
  },
  {
    tmdbId: 24438,
    title: 'Raincoat',
    year: 2004,
    language: 'hindi',
    genres: ['romance', 'drama'],
    tasteTags: ['literary-melancholy', 'soft-romance'],
    matchNote: 'Two people, one afternoon, and a lifetime of what-ifs. Restrained and devastating.',
  },
  {
    tmdbId: 11104,
    title: 'Kung Fu Panda',
    year: 2008,
    language: 'english',
    genres: ['animation', 'comedy', 'action'],
    tasteTags: ['whimsical', 'comfort-cute'],
    matchNote: 'A panda who dreamed. Also — it\'s not a cartoon, it\'s a philosophy. Inner peace.',
  },
  {
    tmdbId: 10153,
    title: 'Rockstar',
    year: 2011,
    language: 'hindi',
    genres: ['romance', 'drama', 'music'],
    tasteTags: ['coming-of-age', 'soft-romance'],
    matchNote: 'Love as inspiration, love as destruction. Music, longing, and the price of art.',
  },
  {
    tmdbId: 10997,
    title: 'Aparajito',
    year: 1957,
    language: 'bengali',
    genres: ['drama', 'coming-of-age'],
    tasteTags: ['coming-of-age', 'literary-melancholy'],
    matchNote: 'The second chapter of Apu\'s journey — leaving home, losing a parent, growing up. Ray\'s masterpiece.',
  },
  {
    tmdbId: 140420,
    title: 'Article 15',
    year: 2019,
    language: 'hindi',
    genres: ['drama', 'social-political', 'thriller'],
    tasteTags: ['social-drama'],
    matchNote: 'Anger as art. A film that asks uncomfortable questions and demands answers.',
  },
  {
    tmdbId: 480530,
    title: 'Mimi',
    year: 2021,
    language: 'hindi',
    genres: ['comedy', 'drama'],
    tasteTags: ['social-drama', 'whimsical'],
    matchNote: 'Surrogacy, dreams, and what it means to be a mother. Quirky yet deeply moving.',
  },
  {
    tmdbId: 297,
    title: 'Masaan',
    year: 2015,
    language: 'hindi',
    genres: ['drama', 'romance'],
    tasteTags: ['literary-melancholy', 'social-drama'],
    matchNote: 'Loss, longing, and the search for dignity on the ghats of Varanasi. Poetry in cinema.',
  },
  {
    tmdbId: 569,
    title: 'Bhavesh Joshi Superhero',
    year: 2018,
    language: 'hindi',
    genres: ['action', 'drama', 'social-political'],
    tasteTags: ['social-drama'],
    matchNote: 'The ordinary person\'s responsibility in an unjust system. Vigilantism with a conscience.',
  },
  {
    tmdbId: 9479,
    title: 'Dangal',
    year: 2016,
    language: 'hindi',
    genres: ['drama', 'action', 'biography'],
    tasteTags: ['social-drama', 'thought-provoking'],
    matchNote: 'Father, daughters, dreams, and breaking every rule. Theatrical, emotional, earned.',
  },
  {
    tmdbId: 9593,
    title: 'Jagga Jasoos',
    year: 2017,
    language: 'hindi',
    genres: ['musical', 'adventure', 'comedy'],
    tasteTags: ['whimsical'],
    matchNote: 'Underrated, misunderstood, and wildly inventive. A musical detective story like no other.',
  },
  {
    tmdbId: 949,
    title: 'Jurassic World Dominion',
    year: 2022,
    language: 'english',
    genres: ['action', 'adventure', 'sci-fi'],
    tasteTags: ['whimsical'],
    matchNote: 'Big dinosaurs, bigger spectacle. Sometimes you just need to watch things get chased.',
  },
  {
    tmdbId: 746,
    title: 'KGF 2',
    year: 2022,
    language: 'hindi',
    genres: ['action', 'drama'],
    tasteTags: [],
    matchNote: 'Macho spectacle at its most maximalist. Not your usual taste, but sometimes the gold calls.',
  },
  {
    tmdbId: 343,
    title: '13B',
    year: 2009,
    language: 'hindi',
    genres: ['horror', 'thriller'],
    tasteTags: ['thought-provoking'],
    matchNote: 'A TV that shows the future — and a family trapped in it. Clever, creepy, underrated.',
  },
  {
    tmdbId: 245,
    title: 'Jug Jugg Jeeyo',
    year: 2022,
    language: 'hindi',
    genres: ['comedy', 'drama', 'romance'],
    tasteTags: ['filmy-romance', 'comfort-cute'],
    matchNote: 'Family, divorce, and love in all its messy forms. Entertaining with unexpected heart.',
  },
  {
    tmdbId: 297,
    title: 'Flames',
    year: 2018,
    language: 'hindi',
    genres: ['romance', 'coming-of-age'],
    tasteTags: ['coming-of-age', 'soft-romance'],
    matchNote: 'Tuition classes, first love, and the sweetness of growing up. Nostalgia in every frame.',
  },
  {
    tmdbId: 124903,
    title: 'Hirak Rajar Deshe',
    year: 1980,
    language: 'bengali',
    genres: ['drama', 'social-political', 'whimsical'],
    tasteTags: ['social-drama', 'whimsical'],
    matchNote: 'Satyajit Ray\'s political allegory wrapped in fantasy — a film that fights fascism with imagination.',
  },
  {
    tmdbId: 11866,
    title: 'The Apu Trilogy',
    year: 1959,
    language: 'bengali',
    genres: ['drama', 'coming-of-age'],
    tasteTags: ['coming-of-age', 'literary-melancholy'],
    matchNote: 'The original coming-of-age story. Apu\'s journey from boyhood to manhood is cinema\'s greatest gift.',
  },
  {
    tmdbId: 862,
    title: 'Toy Story',
    year: 1995,
    language: 'english',
    genres: ['animation', 'comedy', 'coming-of-age'],
    tasteTags: ['coming-of-age', 'comfort-cute'],
    matchNote: 'Growing up, letting go, and the toys who taught us how. A perfect comfort watch.',
  },
  {
    tmdbId: 354912,
    title: 'Coco',
    year: 2017,
    language: 'english',
    genres: ['animation', 'drama', 'music'],
    tasteTags: ['comfort-cute', 'thought-provoking'],
    matchNote: 'Remembering those we\'ve lost — and the music that keeps them alive. Have tissues ready.',
  },
  {
    tmdbId: 301,
    title: 'Inside Out',
    year: 2015,
    language: 'english',
    genres: ['animation', 'drama', 'coming-of-age'],
    tasteTags: ['coming-of-age', 'comfort-cute'],
    matchNote: 'Sadness is not the enemy. This film understands emotions better than most humans do.',
  },
  {
    tmdbId: 508947,
    title: 'Turning Red',
    year: 2022,
    language: 'english',
    genres: ['animation', 'coming-of-age', 'comedy'],
    tasteTags: ['coming-of-age', 'whimsical'],
    matchNote: 'A girl turns into a red panda when she feels too much. Chaotic, cute, and deeply felt.',
  },
  {
    tmdbId: 3548,
    title: '3 Idiots',
    year: 2009,
    language: 'hindi',
    genres: ['comedy', 'drama', 'coming-of-age'],
    tasteTags: ['coming-of-age', 'thought-provoking'],
    matchNote: 'Chasing excellence vs chasing success — a film that taught a generation to follow their heart.',
  },
  {
    tmdbId: 1262,
    title: 'Zindagi Na Milegi Dobara',
    year: 2011,
    language: 'hindi',
    genres: ['drama', 'comedy', 'coming-of-age'],
    tasteTags: ['coming-of-age', 'soft-romance'],
    matchNote: 'Friendship, fear, and living fully. A road trip that feels like a deep breath.',
  },
  {
    tmdbId: 10625,
    title: 'Yeh Jawaani Hai Deewani',
    year: 2013,
    language: 'hindi',
    genres: ['romance', 'comedy', 'drama'],
    tasteTags: ['coming-of-age', 'filmy-romance'],
    matchNote: 'Growing up, drifting apart, and finding your way back. Badtameez dil forever.',
  },
  {
    tmdbId: 836,
    title: 'The Lunchbox',
    year: 2013,
    language: 'hindi',
    genres: ['romance', 'drama'],
    tasteTags: ['soft-romance', 'literary-melancholy'],
    matchNote: 'A lunchbox gone astray, and a connection that grows through handwritten notes. Quiet and profound.',
  },
  {
    tmdbId: 240832,
    title: 'Piku',
    year: 2015,
    language: 'hindi',
    genres: ['comedy', 'drama'],
    tasteTags: ['comfort-cute', 'whimsical'],
    matchNote: 'A father-daughter road trip, constipation jokes, and Deepika in a nightie. Perfectly imperfect.',
  },
  {
    tmdbId: 11868,
    title: 'Charulata',
    year: 1964,
    language: 'bengali',
    genres: ['drama', 'romance'],
    tasteTags: ['literary-melancholy', 'soft-romance'],
    matchNote: 'A lonely wife, a charming cousin, and unspoken desires. Ray\'s most exquisitely tender film.',
  },
];
